language: objective-c
osx_image: xcode611

before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- gem install cocoapods

script:
- set -o pipefail
- xcodebuild -project Emoji.xcodeproj -scheme Emoji-iOS test -sdk iphonesimulator | xcpretty -c
- pod lib lint --quick
