language: objective-c
osx_image: xcode10

before_script:
- xcrun simctl list
- SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone XR (12.0) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/" | head -n 1)
- echo $SIMULATOR_ID

script:
- set -o pipefail
- xcodebuild -project Emoji.xcodeproj -scheme Emoji-iOS test -sdk iphonesimulator -destination id=$SIMULATOR_ID | xcpretty -c
- xcodebuild -project Emoji.xcodeproj -scheme Emoji-OSX build -sdk macosx10.14 | xcpretty -c
- pod lib lint --quick
- swift --version
#- swift build
#- swift test

after_success:
- bash <(curl -s https://codecov.io/bash)
