language: objective-c
osx_image: xcode11.3

before_script:
- xcrun simctl list
- SIMULATOR_ID=$(xcrun instruments -s | awk '/iPhone 11 \(13/' | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/" | head -n 1)
- echo $SIMULATOR_ID

script:
- set -o pipefail
- xcodebuild -project Emoji.xcodeproj -scheme Emoji-iOS test -sdk iphonesimulator -destination id=$SIMULATOR_ID | xcpretty -c
- xcodebuild -project Emoji.xcodeproj -scheme Emoji-OSX build -sdk macosx10.15 | xcpretty -c
- pod lib lint --quick
- swift --version
#- swift build
#- swift test

after_success:
- bash <(curl -s https://codecov.io/bash)
